networks:
  net:
    driver: bridge

services:
  # mysql:
  #   image: mysql:8.0.43-debian
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=headless_cms
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=user
  #   ports:
  #     - "3306:3306"
  #   restart: always
  #   networks:
  #     - net
