version: "3.9"

networks:
  net:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react
    ports:
      - "5173:5173"
    volumes:
      # Map the application code from the host to the container for live updates
      - ./frontend:/app
      # Use an anonymous volume for node_modules to avoid host interference
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - net

  headless_cms_server:
    build:
      context: ./headless_cms/mysite
      dockerfile: Dockerfile
    image: wagtail
    ports:
      - "8000:8000"
    env_file:
      - ./headless_cms/mysite/.env
    depends_on:
      - mysql
    networks:
      - net

  mysql:
    image: mysql:8.0.43-debian
    env_file:
      - ./headless_cms/mysite/.env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net

volumes:
  mysql_data:
